[package]
name = "md5-checksum-rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "md5-checksum-rust"
path = "src/main.rs"

[dependencies]
hex = "0.4.3"
md-5 = "0.10.6"
tokio = { version = "1.48.0", features = ["macros", "fs", "io-util", "rt-multi-thread"] }